server:
  port: 8401
spring:
  application:
    name: admin-server
  security:
    user:
      name: root
      password: root
  #mail配置
  mail:
    host: smtp.qq.com
    username:
    password:
    properties:
      mail:
        smpt:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          to:
          from:
