server:
  port: 8301

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: Zuul-Proxy

#配置zuul路由
zuul:
  routes:
    user-consumer: /apigateway/user/**
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000