server:
  port: 8301

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: Zuul-Proxy

#配置zuul路由
zuul:
  routes:
    user-consumer: /apigateway/user/**
    user-provider:
      path: /user/provider/**
      #写死一个url无法做负载均衡，hystrix也会失效
      #url: http://localhost:8103
      #使用ribbon实现负载均衡
      ribbon:
        listOfServers: localhost:8103,localhost:8104
    mashibing:
      path: /mashibing/**
      url: http://www.mashibing.com
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
    #忽略微服务
  ignored-services: eureka-server

ribbon:
  ReadTimeout: 10000
  ConnectionTimeout: 10000

#改变服务的负载均衡策略
user-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#配置actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    routes:
      enabled: true