server:
  port: 8101
eureka:
  client:
    #开启actuator上报真实的健康状态
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    metadata-map:
      username: zhangsan
      age: 80
spring:
  application:
    name: Eureka-provider

#actuator输出所有的端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
