server:
  port: 8203
  instance:
spring:
  application:
    name: User-Consumer
  #使用zipkin收集链路数据
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      rate: 1
      probability: 1

#定义负载均衡策略
provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#ribbon脱离eureka使用
#ribbon:
#  eureka:
#    enabled: false
#  listOfServers: peer1:8081,peer2:8082

#配置ribbon的重试机制
ribbon:
  #连接超时时间
  ConnectionTimeout: 1000
  #业务处理时间（获取数据的超时时间）
  ReadTimeout: 2000
  #同一台实例的最大重试次数（不包含首次调用）
  MaxAutoRetries: 1
  #重试负载均衡其他实例的最大重试次数（不包含首次调用）
  MaxAutoRetriesNextServers: 3
  #是否所有操作都重试
  OkToRetryOnAllOperations: false

#feign启用hystrix
feign:
  hystrix:
    enabled: true

#actuator输出所有的端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

#hystrix使用信号量
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
