server:
  port: 8104
eureka:
  client:
    #开启actuator上报真实的健康状态
    healthcheck:
      enabled: true
    service-url:
      #defaultZone: http://test:123@localhost:8080/eureka/
      defaultZone: http://localhost:8080/eureka/
  instance:
    metadata-map:
      username: zhangsan
      age: 80
spring:
  application:
    name: User-Provider
    #使用zipkin收集链路数据
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      rate: 1
      probability: 1

#actuator输出所有的端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
        #开启远程停止微服务
  endpoint:
    shutdown:
      enabled: true
