server:
  port: 8083
spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://peer2:8082/eureka/,http://peer1:8081/eureka/
