eureka:
  client:
    service-url:
      defaultZone: http://peer1:8081/eureka/,http://peer1:8082/eureka/,http://peer1:8083/eureka/
spring:
  application:
    name: Eureka-provider
  profiles:
    active: peer1