server:
  port: 8080

spring:
  application:
    name: eureka-server
  security:
    user:
      name: test
      password: 123
      roles: SUPERUSER
eureka:
  client:
    #eureka server不需要向自己注册，也不需要获取注册信息
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      #defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8080/eureka/
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost
    metadata-map:
      dalao: mashibing
  #关闭自我保护
  server:
    enable-self-preservation: false
