server:
  port: 8202
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8081/eureka/,http://peer1:8082/eureka/,http://peer1:8083/eureka/
  instance:
spring:
  application:
    name: Eureka-Consumer